// File: scrambler.v
// Generated by MyHDL 0.11
// Date: Tue Mar 28 14:39:03 2023


`timescale 1ns/10ps

module scrambler (
    din,
    dout,
    clk,
    reset
);


input [6:0] din;
output [6:0] dout;
wire [6:0] dout;
input clk;
input reset;

reg [6:0] state;
reg [6:0] dout_reg;



always @(posedge clk, negedge reset) begin: SCRAMBLER_SCRAMBLE_LOGIC
    if (reset == 0) begin
        dout_reg <= 0;
        state <= 0;
    end
    else begin
        if (reset) begin
            state <= 7'h7f;
        end
        else begin
            state <= 1'b0;
        end
        dout_reg <= dout_reg;
    end
end



assign dout = dout_reg;

endmodule
